### PR TITLE
Fixed plugin to work in kicad 7

### LINKED ISSUE #2: Plugin doesn't work in KiCad 7.0.1
When trying to use plugin under KiCad 7.0.1 on Linux, the plugin loading fails with:

```
Traceback (most recent call last):

  File "/home/kajus/.config/kicad/7.0/scripting/kicad_spiral_plugin/kicad_spiral_plugin.py", line 243, in Run
    MyFrame(None).ShowWithEffect(wx.SHOW_EFFECT_EXPAND,200)
    ^^^^^^^^^^^^^

  File "/home/kajus/.config/kicad/7.0/scripting/kicad_spiral_plugin/kicad_spiral_plugin.py", line 14, in __init__
    topPanel = MyPanel(self)
               ^^^^^^^^^^^^^

  File "/home/kajus/.config/kicad/7.0/scripting/kicad_spiral_plugin/kicad_spiral_plugin.py", line 67, in __init__
    layers.append(pcbnew.BOARD_GetStandardLayerName(i))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: module 'pcbnew' has no attribute 'BOARD_GetStandardLayerName'
```

Any idea what could be the cause?

### PR DESCRIPTION
**Pull request by kajusK**
Closes #2.

Not sure how it was implemented in kicad 6, but now the pcbnew.BOARD is a class with GetStandardLayerName method.

### CODE REVIEW

**Comment by tristanitschner** [comment]
While the fix looks good, it does break backward compatibility, so I will not pull it. I will take a look at it once I have some time.

**Comment by tristanitschner** [comment]
The plugin works using the newest KiCAD version 7.99 in its current state. Won't fix.
