### ISSUE TITLE
Plugin does not work in KiCad 8.0.2

### ISSUE THREAD

**Issue by mbiselx** [tristanitschner/kicad_spiral_plugin#4]
When running the plugin in KiCad 8.0.2 on Windows, I get the same error as in #2 : 
`AttributeError: module 'pcbnew' has no attribute 'BOARD_GetStandardLayerName'`

Apparently the fix for #2 only works for KiCad 7.0.*

**Comment by tristanitschner** [comment]
Yeah, classic case of Kicad namespace mangling. They often do change things, which breaks backwards compatibility, and then they roll back (see other Kicad plugins).

Unfortunately I do not have access to a Windows machine and also I'm very busy as of right now.

If you come up with a fix that does not break backwards compatibility (using version check, although I really don't like it), I would be happy to merge it. Maybe all that's needed is to include version 8.0 in the existing version check.

**Comment by mbiselx** [comment]
Yes, it does seem to be a common issue. 
I think I found a work-around that does not require a version check, as it gets the layer names directly from the current Board object. This seems to be compatible with KiCAD versions 6.0 - 8.0. I can't tell for earlier versions though.

**Comment by tristanitschner** [comment]
Should by fixed by [ac119a2](https://github.com/tristanitschner/kicad_spiral_plugin/commit/ac119a292c0a921b2830ed769ab9bab64e092ccf).
