### ISSUE TITLE
Plugin doesn't work in KiCad 7.0.1

### ISSUE THREAD

**Issue by kajusK** [tristanitschner/kicad_spiral_plugin#2]
When trying to use plugin under KiCad 7.0.1 on Linux, the plugin loading fails with:

```
Traceback (most recent call last):

  File "/home/kajus/.config/kicad/7.0/scripting/kicad_spiral_plugin/kicad_spiral_plugin.py", line 243, in Run
    MyFrame(None).ShowWithEffect(wx.SHOW_EFFECT_EXPAND,200)
    ^^^^^^^^^^^^^

  File "/home/kajus/.config/kicad/7.0/scripting/kicad_spiral_plugin/kicad_spiral_plugin.py", line 14, in __init__
    topPanel = MyPanel(self)
               ^^^^^^^^^^^^^

  File "/home/kajus/.config/kicad/7.0/scripting/kicad_spiral_plugin/kicad_spiral_plugin.py", line 67, in __init__
    layers.append(pcbnew.BOARD_GetStandardLayerName(i))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: module 'pcbnew' has no attribute 'BOARD_GetStandardLayerName'
```

Any idea what could be the cause?

**Comment by tristanitschner** [comment]
The issue will not be addressed, due to the plugin working with the newest KiCAD 7.99 release. I would advise you to upgrade.

**Comment by kajusK** [comment]
The latest stable KiCad release is the 7.0.2 (https://www.kicad.org/blog/2023/04/KiCad-7.0.2-Release/), latest available release is KiCad 7.0.4 (from KiCad repo tags), the original plugin code doesn't work in any of them.

From what I understand, the 7.99 is a branch for future KiCad 8 development (https://gitlab.com/kicad/code/kicad/-/commit/76e224e0af755c9491f7c42b44e96b7008fd0b68), so everyone using the latest stable kicad version won't be able to use your plugin.

**Comment by tristanitschner** [comment]
Ok fair enough. I wasn't able to install KiCad via adding the 7.0 repository and installing using apt. Nonetheless, I tried a fix in 6116d4a, which works with 7.99. Could you test?

**Comment by kajusK** [comment]
It works well in 7.0.1. Thank you!

**Comment by tristanitschner** [comment]
Great!
